feat: scrambling json
shunichi/pgdump-obfuscator pull request #1
Opened 2022-03-07 08:19 UTC by kzkn

2022-03-11 06:50 UTC, shunichi commented on obfuscators.go
> +			s[i] = bytesOutputAlphabet[(sumBytes[(i+index)%sumLength])%bytesOutputAlphabetLength]
ScrambleBytes だと `+byte(r)` があるので、同様にしたほうが良いような気もします。

https://github.com/shunichi/pgdump-obfuscator/blob/fe954c36efc0f99c4a1391451015b5c62cb9334c/obfuscators.go#L63

2022-03-11 06:50 UTC, shunichi commented on obfuscators.go
> +				s[i] = '0' + (sumBytes[(i+index)%sumLength])%10
ここも b の値を使ったほうがよいような気もします。

https://github.com/shunichi/pgdump-obfuscator/blob/fe954c36efc0f99c4a1391451015b5c62cb9334c/obfuscators.go#L112

2022-03-16 15:09 UTC, kzkn commented
@shunichi コメントいただいた点を修正しました！

2022-03-24 04:59 UTC, shunichi requested changes

2022-03-24 04:59 UTC, shunichi commented on obfuscators.go
> +			builder.WriteString("\"" + k + "\":")
k に `"` や `\` などが含まれえていたらエスケープが必要そうです。

![screenshot](https://user-images.githubusercontent.com/1687073/159845379-a086a4b4-c74c-4360-8091-52dd9a2d1626.png)
https://www.json.org/json-en.html

2022-03-24 06:58 UTC, shunichi approved these changes
OK

2022-03-24 06:58 UTC, merged